import type { Candidate, CandidateProject, Job, Skill } from "./types";

const jobRows: Array<
  Omit<Job, "skills" | "id" | "createdAt"> & {
    skills: Array<{ name: string; importance: "required" | "preferred" }>;
  }
> = [
  {
    title: "Frontend Engineer",
    company: "Northstar Labs",
    description:
      "Build accessible, high-performance product experiences for a growing collaboration platform.",
    location: "Bengaluru, India",
    workMode: "hybrid",
    employmentType: "full-time",
    minExperience: 3,
    maxExperience: 6,
    education: "bachelors",
    salaryMin: 1800000,
    salaryMax: 2800000,
    status: "active",
    skills: [
      { name: "React", importance: "required" },
      { name: "TypeScript", importance: "required" },
      { name: "JavaScript", importance: "required" },
      { name: "CSS", importance: "required" },
      { name: "Next.js", importance: "preferred" },
      { name: "Accessibility", importance: "preferred" },
    ],
  },
  {
    title: "Senior Frontend Engineer",
    company: "Lattice Health",
    description:
      "Shape thoughtful patient and clinician workflows across a suite of digital health products.",
    location: "Remote, India",
    workMode: "remote",
    employmentType: "full-time",
    minExperience: 5,
    maxExperience: 9,
    education: "bachelors",
    salaryMin: 2600000,
    salaryMax: 3800000,
    status: "active",
    skills: [
      { name: "React", importance: "required" },
      { name: "TypeScript", importance: "required" },
      { name: "Next.js", importance: "required" },
      { name: "Testing", importance: "required" },
      { name: "Accessibility", importance: "preferred" },
      { name: "GraphQL", importance: "preferred" },
    ],
  },
  {
    title: "UI Engineer",
    company: "Morrow Finance",
    description:
      "Deliver precise, responsive interfaces for a modern personal finance product.",
    location: "Mumbai, India",
    workMode: "onsite",
    employmentType: "full-time",
    minExperience: 2,
    maxExperience: 4,
    education: "any",
    salaryMin: 1400000,
    salaryMax: 2200000,
    status: "active",
    skills: [
      { name: "JavaScript", importance: "required" },
      { name: "React", importance: "required" },
      { name: "HTML", importance: "required" },
      { name: "CSS", importance: "required" },
      { name: "Tailwind CSS", importance: "preferred" },
      { name: "Figma", importance: "preferred" },
    ],
  },
  {
    title: "Backend Engineer",
    company: "Relay Commerce",
    description:
      "Design reliable APIs and services that power high-volume commerce experiences.",
    location: "Pune, India",
    workMode: "hybrid",
    employmentType: "full-time",
    minExperience: 3,
    maxExperience: 6,
    education: "bachelors",
    salaryMin: 1900000,
    salaryMax: 3000000,
    status: "active",
    skills: [
      { name: "Node.js", importance: "required" },
      { name: "PostgreSQL", importance: "required" },
      { name: "REST APIs", importance: "required" },
      { name: "Docker", importance: "required" },
      { name: "Redis", importance: "preferred" },
      { name: "AWS", importance: "preferred" },
    ],
  },
  {
    title: "Python Backend Developer",
    company: "Aster Analytics",
    description:
      "Build dependable data services and integrations for enterprise analytics teams.",
    location: "Hyderabad, India",
    workMode: "remote",
    employmentType: "full-time",
    minExperience: 2,
    maxExperience: 5,
    education: "bachelors",
    salaryMin: 1600000,
    salaryMax: 2600000,
    status: "active",
    skills: [
      { name: "Python", importance: "required" },
      { name: "PostgreSQL", importance: "required" },
      { name: "REST APIs", importance: "required" },
      { name: "Docker", importance: "required" },
      { name: "Redis", importance: "preferred" },
      { name: "AWS", importance: "preferred" },
    ],
  },
  {
    title: "Platform API Engineer",
    company: "Cirrus Mobility",
    description:
      "Own API reliability and developer tooling for a multi-sided mobility platform.",
    location: "Delhi NCR, India",
    workMode: "hybrid",
    employmentType: "full-time",
    minExperience: 4,
    maxExperience: 7,
    education: "bachelors",
    salaryMin: 2200000,
    salaryMax: 3400000,
    status: "active",
    skills: [
      { name: "Node.js", importance: "required" },
      { name: "GraphQL", importance: "required" },
      { name: "PostgreSQL", importance: "required" },
      { name: "Redis", importance: "required" },
      { name: "Kubernetes", importance: "preferred" },
      { name: "CI/CD", importance: "preferred" },
    ],
  },
  {
    title: "Data Analyst",
    company: "Goodwell Energy",
    description:
      "Turn operational data into clear reporting that helps teams plan a cleaner grid.",
    location: "Bengaluru, India",
    workMode: "hybrid",
    employmentType: "full-time",
    minExperience: 2,
    maxExperience: 4,
    education: "bachelors",
    salaryMin: 1300000,
    salaryMax: 2100000,
    status: "active",
    skills: [
      { name: "SQL", importance: "required" },
      { name: "Python", importance: "required" },
      { name: "Tableau", importance: "required" },
      { name: "Excel", importance: "required" },
      { name: "Power BI", importance: "preferred" },
      { name: "Pandas", importance: "preferred" },
    ],
  },
  {
    title: "Product Data Analyst",
    company: "Tandem Learning",
    description:
      "Help product teams understand learner behavior through rigorous analysis and storytelling.",
    location: "Remote, India",
    workMode: "remote",
    employmentType: "full-time",
    minExperience: 3,
    maxExperience: 6,
    education: "bachelors",
    salaryMin: 1700000,
    salaryMax: 2600000,
    status: "active",
    skills: [
      { name: "SQL", importance: "required" },
      { name: "Python", importance: "required" },
      { name: "Pandas", importance: "required" },
      { name: "Tableau", importance: "required" },
      { name: "dbt", importance: "preferred" },
      { name: "Statistics", importance: "preferred" },
    ],
  },
  {
    title: "Business Intelligence Analyst",
    company: "Cedar Retail",
    description:
      "Create trusted dashboards and datasets for merchandising and operations leaders.",
    location: "Chennai, India",
    workMode: "onsite",
    employmentType: "full-time",
    minExperience: 2,
    maxExperience: 5,
    education: "any",
    salaryMin: 1200000,
    salaryMax: 2000000,
    status: "active",
    skills: [
      { name: "SQL", importance: "required" },
      { name: "Power BI", importance: "required" },
      { name: "Excel", importance: "required" },
      { name: "Data modeling", importance: "required" },
      { name: "Python", importance: "preferred" },
      { name: "Snowflake", importance: "preferred" },
    ],
  },
  {
    title: "DevOps Engineer",
    company: "OrbitStack",
    description:
      "Make deployments safer and infrastructure easier to operate for product teams.",
    location: "Pune, India",
    workMode: "hybrid",
    employmentType: "full-time",
    minExperience: 3,
    maxExperience: 6,
    education: "bachelors",
    salaryMin: 2000000,
    salaryMax: 3200000,
    status: "active",
    skills: [
      { name: "AWS", importance: "required" },
      { name: "Docker", importance: "required" },
      { name: "Kubernetes", importance: "required" },
      { name: "Terraform", importance: "required" },
      { name: "Linux", importance: "preferred" },
      { name: "CI/CD", importance: "preferred" },
    ],
  },
  {
    title: "Cloud Infrastructure Engineer",
    company: "Aperture Systems",
    description:
      "Build resilient cloud foundations for teams moving critical workloads to AWS.",
    location: "Remote, India",
    workMode: "remote",
    employmentType: "full-time",
    minExperience: 4,
    maxExperience: 8,
    education: "bachelors",
    salaryMin: 2400000,
    salaryMax: 3800000,
    status: "active",
    skills: [
      { name: "AWS", importance: "required" },
      { name: "Terraform", importance: "required" },
      { name: "Linux", importance: "required" },
      { name: "CI/CD", importance: "required" },
      { name: "Kubernetes", importance: "preferred" },
      { name: "Prometheus", importance: "preferred" },
    ],
  },
  {
    title: "Site Reliability Engineer",
    company: "Beacon Health",
    description:
      "Improve service health, observability, and incident response for a care platform.",
    location: "Hyderabad, India",
    workMode: "hybrid",
    employmentType: "full-time",
    minExperience: 4,
    maxExperience: 7,
    education: "bachelors",
    salaryMin: 2300000,
    salaryMax: 3600000,
    status: "active",
    skills: [
      { name: "Linux", importance: "required" },
      { name: "AWS", importance: "required" },
      { name: "Docker", importance: "required" },
      { name: "Prometheus", importance: "required" },
      { name: "Kubernetes", importance: "preferred" },
      { name: "Python", importance: "preferred" },
    ],
  },
  {
    title: "Full-Stack Engineer",
    company: "Commonplace",
    description:
      "Build end-to-end features for a platform that helps local communities organize.",
    location: "Bengaluru, India",
    workMode: "hybrid",
    employmentType: "full-time",
    minExperience: 3,
    maxExperience: 6,
    education: "bachelors",
    salaryMin: 1900000,
    salaryMax: 3000000,
    status: "active",
    skills: [
      { name: "React", importance: "required" },
      { name: "TypeScript", importance: "required" },
      { name: "Node.js", importance: "required" },
      { name: "PostgreSQL", importance: "required" },
      { name: "AWS", importance: "preferred" },
      { name: "GraphQL", importance: "preferred" },
    ],
  },
  {
    title: "Product Engineer",
    company: "Mosaic Studio",
    description:
      "Take product ideas from prototype to production across a modern web stack.",
    location: "Remote, India",
    workMode: "remote",
    employmentType: "full-time",
    minExperience: 2,
    maxExperience: 5,
    education: "any",
    salaryMin: 1700000,
    salaryMax: 2700000,
    status: "active",
    skills: [
      { name: "React", importance: "required" },
      { name: "TypeScript", importance: "required" },
      { name: "Node.js", importance: "required" },
      { name: "REST APIs", importance: "required" },
      { name: "Figma", importance: "preferred" },
      { name: "PostgreSQL", importance: "preferred" },
    ],
  },
  {
    title: "Software Engineer, Full Stack",
    company: "Greenline",
    description:
      "Ship customer-facing features and internal tools for a fast-growing climate company.",
    location: "Mumbai, India",
    workMode: "onsite",
    employmentType: "full-time",
    minExperience: 3,
    maxExperience: 7,
    education: "bachelors",
    salaryMin: 2100000,
    salaryMax: 3400000,
    status: "active",
    skills: [
      { name: "JavaScript", importance: "required" },
      { name: "React", importance: "required" },
      { name: "Node.js", importance: "required" },
      { name: "PostgreSQL", importance: "required" },
      { name: "Docker", importance: "preferred" },
      { name: "Python", importance: "preferred" },
    ],
  },
];

export const seedJobs: Job[] = jobRows.map((job, index) => ({
  ...job,
  id: `job-${String(index + 1).padStart(3, "0")}`,
  createdAt: "2026-09-18T09:00:00.000Z",
}));

const names = [
  "Aarav Mehta",
  "Mira Shah",
  "Rohan Iyer",
  "Nisha Rao",
  "Kabir Malhotra",
  "Ananya Menon",
  "Dev Patel",
  "Ishita Kapoor",
  "Arjun Nair",
  "Sana Qureshi",
  "Vihaan Kulkarni",
  "Tara Banerjee",
  "Neel Desai",
  "Diya Reddy",
  "Kunal Sethi",
  "Aditi Bose",
  "Ibrahim Khan",
  "Meera Joshi",
  "Aditya Pillai",
  "Saanvi Arora",
  "Rahul Bhat",
  "Pooja Krishnan",
  "Yash Agarwal",
  "Leela Fernandes",
  "Om Prakash",
  "Riya Chawla",
  "Siddharth Roy",
  "Kavya Shetty",
  "Manav Jain",
  "Zoya Thomas",
  "Parth Shah",
  "Maya Suresh",
  "Rehan Siddiqui",
  "Ira Ghosh",
  "Nikhil Verma",
  "Tanvi Deshmukh",
  "Atharv Das",
  "Sia Bhandari",
  "Jayant Rao",
  "Noor Ansari",
];

const roleTracks = [
  {
    headline: "Frontend engineer",
    skills: [
      "React",
      "TypeScript",
      "JavaScript",
      "CSS",
      "HTML",
      "Next.js",
      "Tailwind CSS",
      "Accessibility",
      "Testing",
      "Figma",
    ],
  },
  {
    headline: "Backend engineer",
    skills: [
      "Node.js",
      "Python",
      "PostgreSQL",
      "REST APIs",
      "Docker",
      "Redis",
      "GraphQL",
      "AWS",
      "Linux",
      "CI/CD",
    ],
  },
  {
    headline: "Data analyst",
    skills: [
      "SQL",
      "Python",
      "Tableau",
      "Excel",
      "Power BI",
      "Pandas",
      "dbt",
      "Statistics",
      "Snowflake",
      "Data modeling",
    ],
  },
  {
    headline: "DevOps engineer",
    skills: [
      "AWS",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Linux",
      "CI/CD",
      "Prometheus",
      "Python",
      "PostgreSQL",
      "GitHub Actions",
    ],
  },
  {
    headline: "Full-stack engineer",
    skills: [
      "React",
      "TypeScript",
      "Node.js",
      "PostgreSQL",
      "AWS",
      "Docker",
      "GraphQL",
      "Next.js",
      "REST APIs",
      "JavaScript",
    ],
  },
];

const locations = [
  "Bengaluru, India",
  "Mumbai, India",
  "Hyderabad, India",
  "Pune, India",
  "Delhi NCR, India",
  "Chennai, India",
  "Remote, India",
];

const educationLevels: Candidate["education"][] = [
  "diploma",
  "bachelors",
  "bachelors",
  "masters",
  "bachelors",
  "phd",
];

const realDevelopers: Array<{
  name: string;
  githubUsername: string;
  headline: string;
  location: string;
  experienceYears: number;
  education: Candidate["education"];
  bio: string;
  publicRepos: number;
  followers: number;
  skills: Array<{ name: string; proficiency: Skill["proficiency"]; yearsExperience: number; verified: boolean; verificationScore?: number }>;
  projects: CandidateProject[];
}> = [
  {
    name: "Vasudev",
    githubUsername: "vasudev196006",
    headline: "AI & Full-Stack Systems Engineer",
    location: "Bengaluru, India",
    experienceYears: 3.5,
    education: "bachelors",
    bio: "Full-stack and AI engineer building deterministic career matching, LLM tooling, and production web applications. Passionate about verifiable engineering and open source.",
    publicRepos: 18,
    followers: 42,
    skills: [
      { name: "React", proficiency: "expert", yearsExperience: 3.5, verified: true, verificationScore: 98 },
      { name: "TypeScript", proficiency: "expert", yearsExperience: 3.0, verified: true, verificationScore: 96 },
      { name: "Node.js", proficiency: "advanced", yearsExperience: 3.0, verified: true, verificationScore: 94 },
      { name: "Python", proficiency: "advanced", yearsExperience: 2.5, verified: true, verificationScore: 92 },
      { name: "Next.js", proficiency: "advanced", yearsExperience: 2.5, verified: true, verificationScore: 90 },
      { name: "PostgreSQL", proficiency: "intermediate", yearsExperience: 2.0, verified: true, verificationScore: 88 },
      { name: "Docker", proficiency: "intermediate", yearsExperience: 2.0, verified: true, verificationScore: 85 },
      { name: "AWS", proficiency: "intermediate", yearsExperience: 1.5, verified: true, verificationScore: 82 },
    ],
    projects: [
      {
        title: "HireReady Core Platform",
        description: "AI-powered verifiable skills and deterministic career roadmap matching engine.",
        technologies: ["TypeScript", "React", "Node.js", "Vite", "Tailwind CSS"],
        githubUrl: "https://github.com/vasudev196006/hireread",
        liveUrl: "https://hireready.dev",
      },
      {
        title: "Distributed Agent Scheduler",
        description: "Lightweight async background task runner and execution telemetry pipeline.",
        technologies: ["Python", "Docker", "Redis", "FastAPI"],
        githubUrl: "https://github.com/vasudev196006/hireread",
      },
    ],
  },
  {
    name: "Dan Abramov",
    githubUsername: "gaearon",
    headline: "Frontend Architect & React Core Contributor",
    location: "London, UK (Remote)",
    experienceYears: 12.0,
    education: "bachelors",
    bio: "Co-creator of Redux and Create React App. Former React core team member at Meta. Deep focus on user interfaces, state management, and developer empathy.",
    publicRepos: 260,
    followers: 82000,
    skills: [
      { name: "React", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 99 },
      { name: "JavaScript", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 99 },
      { name: "TypeScript", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 96 },
      { name: "CSS", proficiency: "advanced", yearsExperience: 10.0, verified: true, verificationScore: 94 },
      { name: "Next.js", proficiency: "expert", yearsExperience: 5.0, verified: true, verificationScore: 95 },
    ],
    projects: [
      {
        title: "Redux State Container",
        description: "Predictable state container for JavaScript apps with deterministic state mutation.",
        technologies: ["JavaScript", "TypeScript", "React"],
        githubUrl: "https://github.com/reduxjs/redux",
        liveUrl: "https://redux.js.org",
      },
      {
        title: "Overreacted",
        description: "Personal blog dissecting modern React paradigms and computer science fundamentals.",
        technologies: ["React", "Gatsby", "JavaScript"],
        githubUrl: "https://github.com/gaearon/overreacted.io",
        liveUrl: "https://overreacted.io",
      },
    ],
  },
  {
    name: "shadcn",
    githubUsername: "shadcn",
    headline: "UI Systems Architect & Design Engineer",
    location: "San Francisco, CA (Remote)",
    experienceYears: 8.0,
    education: "bachelors",
    bio: "Creator of shadcn/ui. Specializing in accessible design systems, Tailwind CSS, Radix UI primitives, and beautiful developer-first component libraries.",
    publicRepos: 110,
    followers: 65000,
    skills: [
      { name: "React", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 99 },
      { name: "TypeScript", proficiency: "expert", yearsExperience: 7.0, verified: true, verificationScore: 98 },
      { name: "Tailwind CSS", proficiency: "expert", yearsExperience: 6.0, verified: true, verificationScore: 99 },
      { name: "Next.js", proficiency: "expert", yearsExperience: 6.0, verified: true, verificationScore: 97 },
      { name: "Accessibility", proficiency: "expert", yearsExperience: 7.0, verified: true, verificationScore: 95 },
      { name: "Figma", proficiency: "advanced", yearsExperience: 5.0, verified: true, verificationScore: 92 },
    ],
    projects: [
      {
        title: "shadcn/ui",
        description: "Beautifully designed components that you can copy and paste into your apps.",
        technologies: ["TypeScript", "React", "Tailwind CSS", "Radix UI"],
        githubUrl: "https://github.com/shadcn-ui/ui",
        liveUrl: "https://ui.shadcn.com",
      },
      {
        title: "Taxonomy",
        description: "Open source Next.js 13 enterprise application built using the new router and server components.",
        technologies: ["Next.js", "React", "Tailwind CSS"],
        githubUrl: "https://github.com/shadcn-ui/taxonomy",
      },
    ],
  },
  {
    name: "Andrej Karpathy",
    githubUsername: "karpathy",
    headline: "AI & Deep Learning Research Scientist",
    location: "San Francisco Bay Area, CA",
    experienceYears: 14.0,
    education: "phd",
    bio: "Former Director of AI at Tesla and Founding Member at OpenAI. Building foundational neural network primitives and educational deep learning engines.",
    publicRepos: 55,
    followers: 95000,
    skills: [
      { name: "Python", proficiency: "expert", yearsExperience: 14.0, verified: true, verificationScore: 99 },
      { name: "PyTorch", proficiency: "expert", yearsExperience: 9.0, verified: true, verificationScore: 99 },
      { name: "Machine Learning", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 99 },
      { name: "Data Science", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 97 },
      { name: "C/C++", proficiency: "expert", yearsExperience: 11.0, verified: true, verificationScore: 95 },
    ],
    projects: [
      {
        title: "nanoGPT",
        description: "The simplest, fastest repository for training and finetuning medium-sized GPTs.",
        technologies: ["Python", "PyTorch", "CUDA"],
        githubUrl: "https://github.com/karpathy/nanoGPT",
      },
      {
        title: "micrograd",
        description: "A tiny scalar-valued autograd engine and neural network library with a PyTorch-like API.",
        technologies: ["Python", "Math"],
        githubUrl: "https://github.com/karpathy/micrograd",
      },
    ],
  },
  {
    name: "Salvatore Sanfilippo",
    githubUsername: "antirez",
    headline: "Principal Systems Architect & Database Creator",
    location: "Sicily, Italy (Remote)",
    experienceYears: 20.0,
    education: "bachelors",
    bio: "Creator of Redis in-memory data store. Systems programming, networking protocols, low-latency algorithms, and database internals.",
    publicRepos: 95,
    followers: 48000,
    skills: [
      { name: "Redis", proficiency: "expert", yearsExperience: 15.0, verified: true, verificationScore: 100 },
      { name: "C/C++", proficiency: "expert", yearsExperience: 20.0, verified: true, verificationScore: 99 },
      { name: "Linux", proficiency: "expert", yearsExperience: 18.0, verified: true, verificationScore: 98 },
      { name: "Networking", proficiency: "expert", yearsExperience: 18.0, verified: true, verificationScore: 97 },
      { name: "PostgreSQL", proficiency: "advanced", yearsExperience: 10.0, verified: true, verificationScore: 92 },
    ],
    projects: [
      {
        title: "Redis",
        description: "In-memory database that persists on disk. The data model is key-value with rich data structures.",
        technologies: ["C", "Networking", "Distributed Systems"],
        githubUrl: "https://github.com/redis/redis",
        liveUrl: "https://redis.io",
      },
      {
        title: "smallchat",
        description: "Minimalist chat server in ~200 lines of C for teaching network sockets.",
        technologies: ["C", "Sockets"],
        githubUrl: "https://github.com/antirez/smallchat",
      },
    ],
  },
  {
    name: "Kelsey Hightower",
    githubUsername: "kelseyhightower",
    headline: "Cloud Native & DevOps Architect",
    location: "Portland, OR (Remote)",
    experienceYears: 18.0,
    education: "bachelors",
    bio: "Former Principal Engineer at Google Cloud. Cloud native advocate, Kubernetes educator, speaker, and author of Kubernetes Up and Running.",
    publicRepos: 88,
    followers: 52000,
    skills: [
      { name: "Kubernetes", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 100 },
      { name: "Docker", proficiency: "expert", yearsExperience: 11.0, verified: true, verificationScore: 99 },
      { name: "AWS", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 98 },
      { name: "Linux", proficiency: "expert", yearsExperience: 16.0, verified: true, verificationScore: 98 },
      { name: "CI/CD", proficiency: "expert", yearsExperience: 14.0, verified: true, verificationScore: 96 },
      { name: "Terraform", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 95 },
    ],
    projects: [
      {
        title: "Kubernetes The Hard Way",
        description: "Bootstrap Kubernetes the hard way on bare infrastructure without automated installers.",
        technologies: ["Kubernetes", "Linux", "Networking"],
        githubUrl: "https://github.com/kelseyhightower/kubernetes-the-hard-way",
      },
      {
        title: "nocode",
        description: "The best way to write secure and reliable applications. Write nothing; deploy nowhere.",
        technologies: ["DevOps", "Reliability"],
        githubUrl: "https://github.com/kelseyhightower/nocode",
      },
    ],
  },
  {
    name: "Guillermo Rauch",
    githubUsername: "rauchg",
    headline: "CEO at Vercel & Distributed Cloud Platform Architect",
    location: "San Francisco, CA",
    experienceYears: 15.0,
    education: "bachelors",
    bio: "CEO at Vercel. Creator of Socket.io, Mongoose, and early Next.js architect. Passionate about edge computation, instantaneous web deployments, and DX.",
    publicRepos: 240,
    followers: 61000,
    skills: [
      { name: "Next.js", proficiency: "expert", yearsExperience: 9.0, verified: true, verificationScore: 100 },
      { name: "React", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 98 },
      { name: "TypeScript", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 97 },
      { name: "Node.js", proficiency: "expert", yearsExperience: 13.0, verified: true, verificationScore: 98 },
      { name: "AWS", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 95 },
    ],
    projects: [
      {
        title: "Next.js",
        description: "The React Framework for the Web with Server Components and Edge Middleware.",
        technologies: ["TypeScript", "React", "Rust"],
        githubUrl: "https://github.com/vercel/next.js",
        liveUrl: "https://nextjs.org",
      },
      {
        title: "Socket.IO",
        description: "Real-time bidirectional event-based communication library for web browsers and Node.",
        technologies: ["JavaScript", "WebSockets"],
        githubUrl: "https://github.com/socketio/socket.io",
        liveUrl: "https://socket.io",
      },
    ],
  },
  {
    name: "Evan You",
    githubUsername: "yyx990803",
    headline: "Frontend Architecture & Build Tool Creator",
    location: "Singapore (Remote)",
    experienceYears: 12.0,
    education: "masters",
    bio: "Creator of Vue.js, Vite, and Rolldown. Independent open source developer focusing on progressive frontend frameworks and lightning-fast developer tooling.",
    publicRepos: 180,
    followers: 94000,
    skills: [
      { name: "JavaScript", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 100 },
      { name: "TypeScript", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 98 },
      { name: "Vue.js", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 100 },
      { name: "HTML", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 98 },
      { name: "CSS", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 97 },
    ],
    projects: [
      {
        title: "Vue.js Core",
        description: "Progressive, incrementally-adoptable framework for building UI on the web.",
        technologies: ["TypeScript", "JavaScript"],
        githubUrl: "https://github.com/vuejs/core",
        liveUrl: "https://vuejs.org",
      },
      {
        title: "Vite",
        description: "Next Generation Frontend Tooling powered by native ES modules.",
        technologies: ["TypeScript", "Rollup", "ESBuild"],
        githubUrl: "https://github.com/vitejs/vite",
        liveUrl: "https://vitejs.dev",
      },
    ],
  },
  {
    name: "Theo Browne",
    githubUsername: "t3dotgg",
    headline: "Full-Stack TypeScript & Cloud Edge Specialist",
    location: "San Francisco, CA (Remote)",
    experienceYears: 9.0,
    education: "bachelors",
    bio: "Creator of create-t3-app and Ping.gg. Focus on type safety across the entire stack, Next.js, Prisma, Tailwind, and high-velocity shipping.",
    publicRepos: 140,
    followers: 43000,
    skills: [
      { name: "TypeScript", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 99 },
      { name: "React", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 98 },
      { name: "Next.js", proficiency: "expert", yearsExperience: 6.0, verified: true, verificationScore: 97 },
      { name: "Tailwind CSS", proficiency: "expert", yearsExperience: 5.0, verified: true, verificationScore: 96 },
      { name: "PostgreSQL", proficiency: "advanced", yearsExperience: 6.0, verified: true, verificationScore: 91 },
      { name: "Docker", proficiency: "advanced", yearsExperience: 5.0, verified: true, verificationScore: 89 },
    ],
    projects: [
      {
        title: "create-t3-app",
        description: "The best way to start a full-stack, typesafe Next.js application.",
        technologies: ["TypeScript", "Next.js", "Prisma", "Tailwind CSS"],
        githubUrl: "https://github.com/t3-oss/create-t3-app",
        liveUrl: "https://create.t3.gg",
      },
    ],
  },
  {
    name: "Rich Harris",
    githubUsername: "rich-harris",
    headline: "Frontend Compiler & Svelte Creator",
    location: "New York, NY (Remote)",
    experienceYears: 13.0,
    education: "bachelors",
    bio: "Creator of Svelte, Rollup, and Ractive. Principal Software Engineer at Vercel. Passionate about simplifying web development through smart compilation.",
    publicRepos: 160,
    followers: 45000,
    skills: [
      { name: "JavaScript", proficiency: "expert", yearsExperience: 13.0, verified: true, verificationScore: 100 },
      { name: "TypeScript", proficiency: "expert", yearsExperience: 7.0, verified: true, verificationScore: 96 },
      { name: "CSS", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 98 },
      { name: "HTML", proficiency: "expert", yearsExperience: 13.0, verified: true, verificationScore: 98 },
      { name: "Accessibility", proficiency: "expert", yearsExperience: 9.0, verified: true, verificationScore: 94 },
    ],
    projects: [
      {
        title: "Svelte",
        description: "Cybernetically enhanced web apps with zero-runtime overhead.",
        technologies: ["TypeScript", "Compiler", "JavaScript"],
        githubUrl: "https://github.com/sveltejs/svelte",
        liveUrl: "https://svelte.dev",
      },
    ],
  },
  {
    name: "Sebastián Ramírez",
    githubUsername: "tiangolo",
    headline: "Python Backend & Async API Creator",
    location: "Berlin, Germany (Remote)",
    experienceYears: 11.0,
    education: "masters",
    bio: "Creator of FastAPI, Typer, and SQLModel. Specializing in high-performance Python backends, type hints, async architectures, and OpenAPI specifications.",
    publicRepos: 130,
    followers: 67000,
    skills: [
      { name: "Python", proficiency: "expert", yearsExperience: 11.0, verified: true, verificationScore: 100 },
      { name: "FastAPI", proficiency: "expert", yearsExperience: 6.0, verified: true, verificationScore: 100 },
      { name: "REST APIs", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 99 },
      { name: "PostgreSQL", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 95 },
      { name: "Docker", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 94 },
    ],
    projects: [
      {
        title: "FastAPI",
        description: "Modern, fast (high-performance), web framework for building APIs with Python 3.8+.",
        technologies: ["Python", "Starlette", "Pydantic"],
        githubUrl: "https://github.com/tiangolo/fastapi",
        liveUrl: "https://fastapi.tiangolo.com",
      },
    ],
  },
  {
    name: "Mitchell Hashimoto",
    githubUsername: "mitchellh",
    headline: "Systems & Infrastructure Automation Pioneer",
    location: "Seattle, WA (Remote)",
    experienceYears: 16.0,
    education: "bachelors",
    bio: "Founder of HashiCorp. Creator of Vagrant, Packer, Terraform, Consul, and Nomad. Systems programmer currently building Ghostty terminal emulator in Zig.",
    publicRepos: 210,
    followers: 39000,
    skills: [
      { name: "Terraform", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 100 },
      { name: "Docker", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 98 },
      { name: "Kubernetes", proficiency: "expert", yearsExperience: 9.0, verified: true, verificationScore: 96 },
      { name: "AWS", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 97 },
      { name: "Linux", proficiency: "expert", yearsExperience: 15.0, verified: true, verificationScore: 98 },
      { name: "CI/CD", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 95 },
    ],
    projects: [
      {
        title: "Terraform Core",
        description: "Infrastructure as Code software tool that provides a consistent CLI workflow to manage cloud services.",
        technologies: ["Go", "HCL", "Cloud APIs"],
        githubUrl: "https://github.com/hashicorp/terraform",
        liveUrl: "https://terraform.io",
      },
    ],
  },
  {
    name: "Addy Osmani",
    githubUsername: "addyosmani",
    headline: "Web Platform & Performance Engineering Lead",
    location: "Mountain View, CA",
    experienceYears: 15.0,
    education: "bachelors",
    bio: "Engineering Lead on Google Chrome. Author of Learning JavaScript Design Patterns and Image Optimization. Specialist in Core Web Vitals and frontend speed.",
    publicRepos: 320,
    followers: 46000,
    skills: [
      { name: "JavaScript", proficiency: "expert", yearsExperience: 15.0, verified: true, verificationScore: 99 },
      { name: "React", proficiency: "expert", yearsExperience: 9.0, verified: true, verificationScore: 96 },
      { name: "TypeScript", proficiency: "advanced", yearsExperience: 6.0, verified: true, verificationScore: 93 },
      { name: "HTML", proficiency: "expert", yearsExperience: 15.0, verified: true, verificationScore: 98 },
      { name: "CSS", proficiency: "expert", yearsExperience: 15.0, verified: true, verificationScore: 97 },
    ],
    projects: [
      {
        title: "Critical Path CSS Generator",
        description: "Extracts & inlines critical-path (above-the-fold) CSS on HTML pages.",
        technologies: ["JavaScript", "Node.js"],
        githubUrl: "https://github.com/addyosmani/critical",
      },
    ],
  },
  {
    name: "Kent C. Dodds",
    githubUsername: "kentcdodds",
    headline: "Testing & Full-Stack React Educator",
    location: "Salt Lake City, UT (Remote)",
    experienceYears: 11.0,
    education: "masters",
    bio: "Creator of Testing Library. Co-founder of EpicWeb.dev and Remix ambassador. Teaching developers how to build resilient web applications.",
    publicRepos: 290,
    followers: 47000,
    skills: [
      { name: "React", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 99 },
      { name: "Testing", proficiency: "expert", yearsExperience: 11.0, verified: true, verificationScore: 100 },
      { name: "TypeScript", proficiency: "expert", yearsExperience: 7.0, verified: true, verificationScore: 96 },
      { name: "JavaScript", proficiency: "expert", yearsExperience: 11.0, verified: true, verificationScore: 98 },
      { name: "Node.js", proficiency: "advanced", yearsExperience: 8.0, verified: true, verificationScore: 92 },
    ],
    projects: [
      {
        title: "React Testing Library",
        description: "Simple and complete React DOM testing utilities that encourage good testing practices.",
        technologies: ["JavaScript", "TypeScript", "React", "Jest"],
        githubUrl: "https://github.com/kentcdodds/react-testing-library",
        liveUrl: "https://testing-library.com",
      },
    ],
  },
  {
    name: "Lee Robinson",
    githubUsername: "leerob",
    headline: "VP of Product & Next.js Ecosystem Architect",
    location: "Des Moines, IA (Remote)",
    experienceYears: 8.0,
    education: "bachelors",
    bio: "VP of Product at Vercel. Specialist in Next.js App Router, React Server Components, serverless databases, and modern web developer experience.",
    publicRepos: 150,
    followers: 41000,
    skills: [
      { name: "Next.js", proficiency: "expert", yearsExperience: 7.0, verified: true, verificationScore: 99 },
      { name: "React", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 97 },
      { name: "TypeScript", proficiency: "expert", yearsExperience: 6.0, verified: true, verificationScore: 95 },
      { name: "Tailwind CSS", proficiency: "expert", yearsExperience: 5.0, verified: true, verificationScore: 96 },
      { name: "PostgreSQL", proficiency: "advanced", yearsExperience: 5.0, verified: true, verificationScore: 90 },
    ],
    projects: [
      {
        title: "leerob.io",
        description: "Personal site and digital garden built with Next.js App Router, React Server Components, and Postgres.",
        technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
        githubUrl: "https://github.com/leerob/site",
        liveUrl: "https://leerob.io",
      },
    ],
  },
  {
    name: "Sindre Sorhus",
    githubUsername: "sindresorhus",
    headline: "Full-Time Open Source Developer & Package Author",
    location: "Oslo, Norway (Remote)",
    experienceYears: 14.0,
    education: "bachelors",
    bio: "Full-time open sourcerer. Author of 1000+ npm packages powering the JavaScript ecosystem. Passionate about clean code, minimalism, and TypeScript.",
    publicRepos: 1100,
    followers: 62000,
    skills: [
      { name: "JavaScript", proficiency: "expert", yearsExperience: 14.0, verified: true, verificationScore: 100 },
      { name: "TypeScript", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 99 },
      { name: "Node.js", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 99 },
      { name: "REST APIs", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 96 },
    ],
    projects: [
      {
        title: "Awesome Lists",
        description: "Curated list of awesome lists covering programming languages, frameworks, and tools.",
        technologies: ["Markdown", "Open Source"],
        githubUrl: "https://github.com/sindresorhus/awesome",
      },
      {
        title: "p-limit",
        description: "Run multiple promise-returning & async functions with concurrency control.",
        technologies: ["TypeScript", "Async"],
        githubUrl: "https://github.com/sindresorhus/p-limit",
      },
    ],
  },
  {
    name: "TJ Holowaychuk",
    githubUsername: "tj",
    headline: "Distributed Systems & Go Architect",
    location: "Victoria, BC (Remote)",
    experienceYears: 16.0,
    education: "bachelors",
    bio: "Creator of Express.js, Koa, Commander.js, Mocha, Apex, and Up. Specialist in minimalist systems architecture, cloud infrastructure, and Go.",
    publicRepos: 580,
    followers: 51000,
    skills: [
      { name: "Node.js", proficiency: "expert", yearsExperience: 13.0, verified: true, verificationScore: 100 },
      { name: "JavaScript", proficiency: "expert", yearsExperience: 16.0, verified: true, verificationScore: 99 },
      { name: "Docker", proficiency: "expert", yearsExperience: 9.0, verified: true, verificationScore: 95 },
      { name: "AWS", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 96 },
      { name: "REST APIs", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 98 },
    ],
    projects: [
      {
        title: "Commander.js",
        description: "The complete solution for node.js command-line interfaces.",
        technologies: ["JavaScript", "Node.js", "CLI"],
        githubUrl: "https://github.com/tj/commander.js",
      },
    ],
  },
  {
    name: "Ricardo Cabello",
    githubUsername: "mrdoob",
    headline: "WebGL & 3D Graphics Pioneer",
    location: "London, UK (Remote)",
    experienceYears: 15.0,
    education: "bachelors",
    bio: "Creator of Three.js. Specializing in WebGL, 3D graphics rendering, shaders, real-time animation, and interactive web experiences.",
    publicRepos: 120,
    followers: 44000,
    skills: [
      { name: "JavaScript", proficiency: "expert", yearsExperience: 15.0, verified: true, verificationScore: 100 },
      { name: "Three.js", proficiency: "expert", yearsExperience: 13.0, verified: true, verificationScore: 100 },
      { name: "HTML", proficiency: "expert", yearsExperience: 15.0, verified: true, verificationScore: 98 },
      { name: "CSS", proficiency: "advanced", yearsExperience: 12.0, verified: true, verificationScore: 92 },
    ],
    projects: [
      {
        title: "Three.js",
        description: "JavaScript 3D Library running in all modern browsers using WebGL and WebGPU.",
        technologies: ["JavaScript", "WebGL", "WebGPU", "GLSL"],
        githubUrl: "https://github.com/mrdoob/three.js",
        liveUrl: "https://threejs.org",
      },
    ],
  },
  {
    name: "Shawn Wang",
    githubUsername: "swyx",
    headline: "AI Engineer & Developer Ecosystem Architect",
    location: "Singapore (Remote)",
    experienceYears: 9.0,
    education: "bachelors",
    bio: "Founder of Latent Space. Creator of smol-ai and the AI Engineer Foundation. Author of The Coding Career Handbook. Helping developers transition to AI engineering.",
    publicRepos: 180,
    followers: 35000,
    skills: [
      { name: "Python", proficiency: "expert", yearsExperience: 6.0, verified: true, verificationScore: 96 },
      { name: "TypeScript", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 97 },
      { name: "React", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 96 },
      { name: "Machine Learning", proficiency: "advanced", yearsExperience: 4.0, verified: true, verificationScore: 92 },
      { name: "Next.js", proficiency: "advanced", yearsExperience: 5.0, verified: true, verificationScore: 94 },
    ],
    projects: [
      {
        title: "smol developer",
        description: "An open source AI developer agent that turns entire app specifications into working codebases.",
        technologies: ["Python", "OpenAI", "FastAPI"],
        githubUrl: "https://github.com/smol-ai/developer",
      },
    ],
  },
  {
    name: "Brandon Keepers",
    githubUsername: "bkeepers",
    headline: "DevOps & GitHub Ecosystem Automation Engineer",
    location: "San Francisco, CA",
    experienceYears: 14.0,
    education: "bachelors",
    bio: "Former Head of Open Source at GitHub. Creator of Probot and dotenv. Specialist in GitHub Actions, CI/CD pipelines, and workflow automation.",
    publicRepos: 190,
    followers: 24000,
    skills: [
      { name: "CI/CD", proficiency: "expert", yearsExperience: 12.0, verified: true, verificationScore: 98 },
      { name: "GitHub Actions", proficiency: "expert", yearsExperience: 6.0, verified: true, verificationScore: 99 },
      { name: "Node.js", proficiency: "expert", yearsExperience: 10.0, verified: true, verificationScore: 96 },
      { name: "Docker", proficiency: "expert", yearsExperience: 8.0, verified: true, verificationScore: 94 },
      { name: "AWS", proficiency: "advanced", yearsExperience: 8.0, verified: true, verificationScore: 90 },
    ],
    projects: [
      {
        title: "Probot",
        description: "A framework for building GitHub Apps to automate and improve your workflow.",
        technologies: ["Node.js", "TypeScript", "GitHub API"],
        githubUrl: "https://github.com/probot/probot",
        liveUrl: "https://probot.github.io",
      },
      {
        title: "dotenv",
        description: "Loads environment variables from .env file into ENV in Ruby apps.",
        technologies: ["Ruby", "DevOps"],
        githubUrl: "https://github.com/bkeepers/dotenv",
      },
    ],
  },
];

const certTypes = [
  { name: "AWS Certified Developer – Associate", issuer: "Amazon Web Services" },
  { name: "Meta Front-End Developer Professional Certificate", issuer: "Meta" },
  { name: "Google Cloud Professional Cloud Architect", issuer: "Google Cloud" },
  { name: "HashiCorp Certified: Terraform Associate", issuer: "HashiCorp" },
  { name: "Certified Kubernetes Administrator (CKA)", issuer: "Cloud Native Computing Foundation" },
  { name: "Deep Learning Specialization", issuer: "DeepLearning.AI" },
];

export const seedCandidates: Candidate[] = realDevelopers.map((dev, index) => {
  const certTpl = certTypes[index % certTypes.length]!;
  const suffix = String(index + 1).padStart(3, "0");
  const certHash = `${index + 10}ab73c9f214${dev.githubUsername}`.padEnd(64, "0");
  
  return {
    id: `candidate-${suffix}`,
    name: dev.name,
    headline: dev.headline,
    location: dev.location,
    experienceYears: dev.experienceYears,
    education: dev.education,
    bio: dev.bio,
    publicRepos: dev.publicRepos,
    followers: dev.followers,
    avatarUrl: `https://github.com/${dev.githubUsername}.png`,
    githubUsername: dev.githubUsername,
    githubUrl: `https://github.com/${dev.githubUsername}`,
    skills: dev.skills.map((s) => ({
      name: s.name,
      proficiency: s.proficiency,
      yearsExperience: s.yearsExperience,
      verified: s.verified,
      verificationScore: s.verificationScore ?? 90,
      category: "Engineering",
    })),
    certifications: [
      {
        name: certTpl.name,
        issuer: certTpl.issuer,
        credentialId: `HR-${suffix}-01`,
        verificationHash: certHash,
        issueDate: `202${(index % 4) + 1}-0${(index % 8) + 1}-15`,
        verified: true,
        reviewStatus: "auto_verified",
        verificationUrl: `https://verify.hireready.dev/cert/HR-${suffix}-01`,
      },
    ],
    projects: dev.projects,
  };
});

export const currentLearner: Candidate = seedCandidates[0];